name: Build APK and Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Build APK
        run: ./gradlew assembleRelease
      - name: Upload APK as Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: app/build/outputs/apk/release/app-release.apk
          tag: ${{ github.ref }}
